apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicalnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magicalnginx
  template:
    metadata:
      labels:
        app: magicalnginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "elvisols/magicalnginx"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
