apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: magicalnginx-ingress
spec:
  rules:
    - host: web.solsng.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: magicalnginx-service
              servicePort: http
    # - host: dashboard.solsng.com
    #   http:
    #     paths:
    #       - path: /*
    #         backend:
    #           serviceName: traefik-ingress-service
    #           servicePort: http